# Generated by Django 5.2.6 on 2025-10-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessages',
            options={'ordering': ['created']},
        ),
    ]
